### ISSUE TITLE
Simple fix on 

### ISSUE THREAD

**Issue by richardmark** [spindro/AP-GCN#1]
On the AP-GCN_demo.ipynb file you have
from model import APGCN
it should be 
from models import APGCN

Otherwise ran well. 
How would you use def load_obj(name) to load a trained/saved pkl file for your code?

Thanks 
Rick

**Comment by spindro** [comment]
Thanks Rick fo the tip.

The load and save functions are there only for the results. You can use the
standard utilities of pytorch to save the entire model or just the weights.

I may consider the introduction for the demo file of the model's
save/restore in the future (aka this afternoon central Europe time) .

Best,

Indro
