### ISSUE TITLE
'GCNConv' has no attribute 'norm'

### ISSUE THREAD

**Issue by DexterZeng** [spindro/AP-GCN#4]
Hi, thanks for sharing the code! 

When running the codes, an error appeared: `AttributeError: type object 'GCNConv' has no attribute 'norm'`

It was from the line `drop_edge_index, drop_norm = GCNConv.norm(drop_edge_index,sz)`

I looked through the [pytorch-geometric documentation](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#module-torch_geometric.nn.conv.message_passing) and there seems to be no "norm()" function for GCNConv. I was wondering what might be the problem? Is there anyway else to implement this step?

Many thanks for your time!

**Comment by spindro** [comment]
Hi, thanks for looking into my work.

Probably is due to a version mismatch.
These are the packages of my conda env:

    - torch-cluster==1.5.4
    - torch-geometric==1.4.3
    - torch-scatter==2.0.4
    - torch-sparse==0.6.3
    - torch-spline-conv==1.2.0

Which versions are you using?

**Comment by DexterZeng** [comment]
Hi, thanks for your reply!

I am using PyTorch 1.4.0 and cuda 10.0 and follow the instructions [here](https://github.com/rusty1s/pytorch_geometric#pytorch-140) for installation on Linux, resulting in the following settings:

torch-cluster==1.5.4
torch-geometric==1.6.0
torch-scatter==2.0.4
torch-sparse==0.6.1
torch-spline-conv==1.2.0

I downgraded torch-geometric to 1.4.3 and it worked! 

Besides, I wonder which kind of GPU you used for training. As the runtime of *AP-GCN_demo.ipynb* on my computer (with GeForce GTX TITAN ) is 42.5782 ± 3.6147, while yours is much faster (27.9021 ± 2.5610). 

Thanks for your time.

**Comment by spindro** [comment]
Hi!

The configuration I've used for the demo is:
GeForce RTX 2060 and 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz.

You're welcome!

**Comment by DexterZeng** [comment]
Thanks for the timely reply!
